shift_length_mins: 15 # The length of each signup shift
max_signups_per_shift: 2 # Maximum number of medics allowed to concurrently signup for a shift

# Allowed signup days. Specify the starting (inclusive) and ending hour (exclusive)
shift_times:
  #Thursday: [1, 13]
  #Friday: [10, 19]
  #Saturday: [11, 12]
  Sunday: [11, 4]
  Sunday: [5, 8]
